import { Bell, BriefcaseBusiness, ChartNoAxesCombined, CheckSquare, ContactRound, LayoutDashboard, LogOut, Menu, Search, Settings, UsersRound } from "lucide-react";
import { NavLink, Outlet, useNavigate } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { logout } from "../store/authSlice";
import type { RootState } from "../store/store";
const nav = [["Dashboard", "/dashboard", LayoutDashboard], ["Customers", "/customers", ContactRound], ["Leads", "/leads", UsersRound], ["Pipeline", "/pipeline", BriefcaseBusiness], ["Projects", "/projects", CheckSquare], ["Analytics", "/analytics", ChartNoAxesCombined], ["Settings", "/settings", Settings]] as const;
export function AppShell() { const dispatch = useDispatch(); const navigate = useNavigate(); const user = useSelector((s: RootState) => s.auth.user); return <div className="min-h-screen bg-slate-50 text-slate-950">
  <aside className="fixed inset-y-0 left-0 z-20 hidden w-72 border-r border-slate-200 bg-white px-4 py-5 lg:block"><div className="mb-8 flex items-center gap-3 px-2"><div className="grid h-10 w-10 place-items-center rounded-lg bg-slate-950 font-bold text-mint">N</div><div><p className="font-semibold">NexaFlow</p><p className="text-xs text-slate-500">CRM + delivery ops</p></div></div><nav className="space-y-1">{nav.map(([label, href, Icon]) => <NavLink key={href} to={href} className={({ isActive }) => `flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${isActive ? "bg-slate-950 text-white" : "text-slate-600 hover:bg-slate-100"}`}><Icon size={18}/>{label}</NavLink>)}</nav></aside>
  <header className="sticky top-0 z-10 border-b border-slate-200 bg-white/95 px-4 py-3 backdrop-blur lg:ml-72"><div className="flex items-center gap-3"><button className="rounded-lg border p-2 lg:hidden" aria-label="Open menu"><Menu size={18}/></button><div className="hidden flex-1 items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 md:flex"><Search size={18}/><input className="w-full bg-transparent text-sm outline-none" placeholder="Search customers, deals, projects..." /></div><NavLink to="/notifications" className="relative rounded-lg border p-2" aria-label="Notifications"><Bell size={18}/><span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-mint" /></NavLink><button onClick={() => navigate("/profile")} className="flex items-center gap-2 rounded-lg border px-2 py-1.5"><span className="grid h-8 w-8 place-items-center rounded-md bg-teal-100 text-sm font-bold text-ocean">{user?.name?.split(" ").map((p) => p[0]).join("").slice(0,2)}</span><span className="hidden text-left text-sm md:block"><b>{user?.name}</b><small className="block text-slate-500">{user?.role}</small></span></button><button onClick={() => { dispatch(logout()); navigate("/login"); }} className="rounded-lg border p-2" aria-label="Logout"><LogOut size={18}/></button></div></header>
  <main className="px-4 py-5 pb-24 lg:ml-72 lg:px-8"><Outlet /></main>
  <nav className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-5 border-t border-slate-200 bg-white px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 lg:hidden">{nav.slice(0,5).map(([label, href, Icon]) => <NavLink key={href} to={href} className={({ isActive }) => `grid place-items-center gap-1 rounded-lg py-1.5 text-[11px] ${isActive ? "text-ocean" : "text-slate-500"}`}><Icon size={19}/><span>{label.split(" ")[0]}</span></NavLink>)}</nav>
</div>; }