import { Plus, RefreshCw } from "lucide-react";
import { MoneyLine, SimpleBars } from "./charts";
import { useAnalyticsQuery, useCreateCustomerMutation, useCreateLeadMutation, useListQuery, useNotificationsQuery, useReadNotificationMutation, useUpdateDealMutation, useUpdateTaskMutation } from "../store/api";
const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
const Page = ({ title, kicker, children }: any) => <section className="space-y-5"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-ocean">{kicker}</p><h1 className="text-2xl font-semibold tracking-tight md:text-3xl">{title}</h1></div>{children}</section>;
const State = ({ isLoading, error, empty }: any) => isLoading ? <div className="skeleton h-28" /> : error ? <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">Something went wrong loading this workspace.</div> : empty ? <div className="rounded-lg border border-dashed p-6 text-slate-500">No records match this view yet.</div> : null;
const Kpi = ({ label, value, tone = "bg-white" }: any) => <div className={`rounded-lg border border-slate-200 ${tone} p-4 shadow-sm`}><p className="text-sm text-slate-500">{label}</p><b className="mt-2 block text-2xl">{value}</b></div>;
export function Dashboard() { const { data, isLoading, error } = useAnalyticsQuery(); const a = data?.data; return <Page title="Command center" kicker="Today"><State isLoading={isLoading} error={error}/>{a && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Pipeline value" value={money(a.totalPipelineValue)} tone="bg-teal-50"/><Kpi label="Won revenue" value={money(a.wonRevenue)}/><Kpi label="Lead conversion" value={a.leadConversionRate + "%"}/><Kpi label="Task completion" value={a.taskCompletionRate + "%"}/></div><div className="grid gap-4 xl:grid-cols-[1.4fr_.9fr]"><div className="panel"><h2>Revenue trend</h2><MoneyLine data={a.revenueByMonth}/></div><div className="panel"><h2>Leads by status</h2><SimpleBars data={a.leadsByStatus}/></div></div></>}</Page>; }
function Records({ resource, title, fields }: any) { const { data, isLoading, error } = useListQuery(resource); const items = data?.data ?? []; return <Page title={title} kicker="Workspace"><State isLoading={isLoading} error={error} empty={!items.length}/><div className="record-grid">{items.map((item: any) => <article key={item.id} className="record-card"><div className="flex items-start justify-between gap-3"><div><h3>{item.company || item.name || item.title}</h3><p>{item.name || item.title}</p></div><span className="badge">{item.status || item.stage || item.priority}</span></div><dl>{fields.map((f: string) => <div key={f}><dt>{f}</dt><dd>{f.toLowerCase().includes("value") ? money(item[f] ?? item.estimatedValue ?? 0) : String(item[f] ?? "-")}</dd></div>)}</dl></article>)}</div></Page>; }
export function Customers() { const [create] = useCreateCustomerMutation(); return <Page title="Customers" kicker="CRM"><button className="primary" onClick={() => create({ name: "Elena Walsh", company: "Walsh Strategy", email: "elena@walsh.test", value: 18000 })}><Plus size={17}/>Create customer</button><Records resource="customers" title="" fields={["email","segment","value"]}/></Page>; }
export function Leads() { const [create] = useCreateLeadMutation(); return <Page title="Leads" kicker="CRM"><button className="primary" onClick={() => create({ name: "Marcus Vale", company: "Vale Systems", email: "marcus@vale.test", estimatedValue: 24000 })}><Plus size={17}/>Create lead</button><Records resource="leads" title="" fields={["email","source","estimatedValue"]}/></Page>; }
export function Deals() { return <Records resource="deals" title="Deals" fields={["value","probability","expectedCloseDate"]}/>; }
export function Pipeline() { const { data } = useListQuery("deals"); const [updateDeal] = useUpdateDealMutation(); const stages = ["NEW","QUALIFIED","PROPOSAL","NEGOTIATION","WON","LOST"]; return <Page title="Sales pipeline" kicker="Kanban"><div className="kanban">{stages.map((stage) => <section key={stage}><h2>{stage}</h2>{(data?.data ?? []).filter((d: any) => d.stage === stage).map((deal: any) => <button className="deal-card" key={deal.id} onClick={() => updateDeal({ id: deal.id, body: { stage: stages[Math.min(stages.indexOf(stage)+1, stages.length-1)], probability: Math.min(deal.probability + 20, 100) } })}><b>{deal.title}</b><span>{money(deal.value)}</span><small>Tap to advance</small></button>)}</section>)}</div></Page>; }
export function Projects() { return <Records resource="projects" title="Projects" fields={["progress","deadline","status"]}/>; }
export function Tasks() { const { data } = useListQuery("tasks"); const [update] = useUpdateTaskMutation(); return <Page title="Tasks" kicker="Delivery"><div className="record-grid">{(data?.data ?? []).map((task: any) => <article key={task.id} className="record-card"><div><h3>{task.title}</h3><p>{task.description}</p></div><div className="mt-3 flex items-center justify-between"><span className="badge">{task.priority}</span><button className="secondary" onClick={() => update({ id: task.id, body: { status: task.status === "COMPLETED" ? "TODO" : "COMPLETED" } })}><RefreshCw size={16}/>{task.status}</button></div></article>)}</div></Page>; }
export function Team() { return <Records resource="team" title="Team" fields={["email","role","title"]}/>; }
export function Notifications() { const { data } = useNotificationsQuery(); const [read] = useReadNotificationMutation(); return <Page title="Notifications" kicker="Inbox"><div className="space-y-3">{(data?.data ?? []).map((n: any) => <button key={n.id} onClick={() => read(n.id)} className={`w-full rounded-lg border p-4 text-left ${n.read ? "bg-white" : "bg-teal-50 border-teal-200"}`}><b>{n.title}</b><p className="text-sm text-slate-600">{n.body}</p></button>)}</div></Page>; }
export function Analytics() { const { data } = useAnalyticsQuery(); const a = data?.data; return <Page title="Analytics" kicker="Reports">{a && <div className="grid gap-4 xl:grid-cols-2"><div className="panel"><h2>Deals by stage</h2><SimpleBars data={a.dealsByStage}/></div><div className="panel"><h2>Revenue by month</h2><MoneyLine data={a.revenueByMonth}/></div><div className="panel xl:col-span-2"><h2>Team productivity</h2><SimpleBars data={a.teamProductivity.map((t: any) => ({ name: t.name, value: t.completed }))}/></div></div>}</Page>; }
export const Settings = () => <Page title="Settings" kicker="Admin"><div className="panel"><h2>Company controls</h2><p className="text-slate-600">Role management, security preferences, pipeline stages, and notification policies are represented in the API and ready for extension.</p></div></Page>;
export const Profile = () => <Page title="Profile" kicker="Account"><div className="panel"><h2>Personal workspace</h2><p className="text-slate-600">Manage your profile, session, and mobile-safe preferences.</p></div></Page>;
